- **Using Scalars**

In [4]:
import numpy as np
lst = [1 , 3 , 8 , 4.9 , 12]
x =np.array(lst)
print(x)

[ 1.   3.   8.   4.9 12. ]


In [5]:
print(x+2)

[ 3.   5.  10.   6.9 14. ]


In [6]:
print(x*2)

[ 2.   6.  16.   9.8 24. ]


- **Arithmetic Operations with Two Arrays**

In [7]:
import numpy as np 
liste_1 = [1,3,5,7]
liste_2 = [2,4,6,8]
dizi_1 = np.array(liste_1)
dizi_2 = np.array(liste_2)
print(dizi_1,dizi_2)

[1 3 5 7] [2 4 6 8]


In [8]:
print(dizi_1 + dizi_2)

[ 3  7 11 15]


In [9]:
print(dizi_1 * dizi_2)

[ 2 12 30 56]


- **Comparison Operators**

In [10]:
import numpy as np
y = np.arange(1,7)
print(y)

[1 2 3 4 5 6]


In [11]:
print(y>3)

[False False False  True  True  True]


In [12]:
print(y>=3)

[False False  True  True  True  True]


In [13]:
print(y!=3)

[ True  True False  True  True  True]


In [14]:
print(y==3)

[False False  True False False False]


In [15]:
a = np.arange(0,10,2)
b = np.arange(0,15,3)
print(a)
print(b)                    #To work with two arrays, the arrays must be the same siz

[0 2 4 6 8]
[ 0  3  6  9 12]


In [16]:
print(a<b)

[False  True  True  True  True]


In [17]:
print(a>=b)

[ True False False False False]


In [18]:
print(a!=b)

[False  True  True  True  True]


In [19]:
print(a==b)

[ True False False False False]


- **Logical Operators**

In [20]:
#1- np.logical_and

import numpy as np
print(np.logical_and(True,True))
print(np.logical_and(True,False))
print(np.logical_and(False,False))

True
False
False


In [21]:
array_1 = np.arange(2,15,3)
print(array_1)

[ 2  5  8 11 14]


In [22]:
print(np.logical_and(array_1>2,array_1<11))

[False  True  True False False]


In [23]:
print(np.logical_and(array_1>=5,array_1<13))

[False  True  True  True False]


In [24]:
#2- np.logical_or

print(np.logical_or(True,True))
print(np.logical_or(True,False))
print(np.logical_or(False,False))

True
True
False


In [25]:
print(array_1)

[ 2  5  8 11 14]


In [26]:
print(np.logical_or(array_1>2,array_1<11))

[ True  True  True  True  True]


In [27]:
print(np.logical_or(array_1>=5,array_1<13))

[ True  True  True  True  True]


- **Trigonometric Functions**

In [6]:
import numpy as np
theta = 30        #define angle
print("cos(theta) =",np.cos(theta))
print("sin(theta) =",np.sin(theta))
print("tan(theta) =",np.tan(theta))
print("cot(theta) =",1/np.tan(theta))

cos(theta) = 0.15425144988758405
sin(theta) = -0.9880316240928618
tan(theta) = -6.405331196646276
cot(theta) = -0.15611995216165922


- **Exponential Functions**

- np.exp(power):   The function itself chooses e as the base
- np.exp2(power):  The function itself chooses 2 as the base
- np.power(base,power):  We choose the base of the function

In [7]:
import numpy as np
array_2 = [1,2,3,4,5]
z = np.array(array_2)
print(z)

[1 2 3 4 5]


In [10]:
print("e^x = ",np.exp(z))     #Choosing the z-series as powers of e

e^x =  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [11]:
print("2^x = ",np.exp2(z))      #Choosing the z-series as powers of 2

2^x =  [ 2.  4.  8. 16. 32.]


In [12]:
print("4^x = ",np.power(4,z))         # Choosing the z-series as powers of 4

4^x =  [   4   16   64  256 1024]


- **Logarithmic Functions**

In [1]:
import numpy as np
array_3 = [10,100,1000]
v = np.array(array_3)
print(v)

[  10  100 1000]


In [2]:
print("ln(v) =  ",np.log(v))

ln(v) =   [2.30258509 4.60517019 6.90775528]


In [4]:
#base = 2
print("log2(v) = ",np.log2(v))

log2(v) =  [3.32192809 6.64385619 9.96578428]


In [5]:
#base = 10
print("log10(v) = ",np.log10(v))

log10(v) =  [1. 2. 3.]


- **Aggregate Functions**

- np.sum : Calculates the sum of the elements
- np.mean : Calculates the average of the elements
- np.std : Calculates the standard deviation
- np.var : Calculates variance 
- np.min : Returns the minimum value
- np.max : Returns the maximum value
- np.argmin : Returns the index of the minimum value
- np.argmax : Returns the index of the maximum value
- np.median : Calculates the median of the elements

In [2]:
import numpy as np
array_4 = [1,2,2,2,3,4,5,8,9,9]
m = np.array(array_4)
print(m)

[1 2 2 2 3 4 5 8 9 9]


In [3]:
print(np.sum(m))
print(np.mean(m))
print(np.std(m))
print(np.var(m))
print(np.min(m))
print(np.max(m))
print(np.argmin(m))
print(np.argmax(m))
print(np.median(m))

45
4.5
2.9410882339705484
8.65
1
9
0
8
3.5
