- **Flatten**

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
a = a.ravel()
print(a)

[1 2 3 4 5 6]


- **Reshape**

In [4]:
b = np.array([[1,2,3],[7,8,9]])
print(b)

[[1 2 3]
 [7 8 9]]


In [5]:
print(b.shape)

(2, 3)


In [6]:
b = b.reshape((3,2))
print(b)

[[1 2]
 [3 7]
 [8 9]]


- **Division (Separation)**

In [7]:
c = np.arange(9)
print(c)

[0 1 2 3 4 5 6 7 8]


In [8]:
c = np.array_split(c,2)
print(c)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8])]


- **Combining**

In [9]:
d = np.array([1,2,3,4])
e = np.array([5,6,7,8])
print(d,e)

[1 2 3 4] [5 6 7 8]


In [10]:
f = np.stack((d,e))       #in row
print(f)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
print(x,y)

[1 2 3 4 5] [5 6 7 8 9]


In [12]:
z = np.stack((x,y),axis=1)      #in column
print(z)

[[1 5]
 [2 6]
 [3 7]
 [4 8]
 [5 9]]
