- **Matrix Creation**

In [1]:
import numpy as np

a = np.matrix(np.random.random((2,2)))
print(a)

[[0.68638339 0.97205206]
 [0.08687603 0.86724842]]


In [3]:
b = np.matrix(np.array([[0,0],[1,1]]))
print(b)

[[0 0]
 [1 1]]


In [4]:
c = np.mat(([1,1],[0,0]))
print(c)

[[1 1]
 [0 0]]


- **Basic Matrix Routines**

1) Getting the Transpose of the Matrix

In [5]:
x = np.mat(([1,2],[3,4]))
print(x)

[[1 2]
 [3 4]]


In [6]:
print(x.T)

[[1 3]
 [2 4]]


2) Getting the Determinant of the Matrix

In [10]:
y = np.mat(([0,1],[2,3]))
print(y)

[[0 1]
 [2 3]]


In [11]:
print(np.linalg.det(y))   #(3*0)-(2+1)

-2.0


- **Matrix Functions**

In [12]:
k = np.mat(([1,2],[3,4]))
print(k)

[[1 2]
 [3 4]]


In [13]:
l = np.mat(np.ones(4).reshape(2,2))
print(l)

[[1. 1.]
 [1. 1.]]


1) Addition

In [14]:
print(k+3)

[[4 5]
 [6 7]]


In [15]:
print(np.add(k,l))

[[2. 3.]
 [4. 5.]]


2) Subtraction

In [16]:
print(k-3)

[[-2 -1]
 [ 0  1]]


In [17]:
print(np.subtract(k,l))

[[0. 1.]
 [2. 3.]]


3) Multiplication

In [18]:
print(k*3)

[[ 3  6]
 [ 9 12]]


In [19]:
print(np.dot(k,l))

[[3. 3.]
 [7. 7.]]


4) Division 

In [20]:
print(k/3)

[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [21]:
print(np.divide(k,l))

[[1. 2.]
 [3. 4.]]
