- **Using Scalars**

In [4]:
import numpy as np
lst = [1 , 3 , 8 , 4.9 , 12]
x =np.array(lst)
print(x)

[ 1.   3.   8.   4.9 12. ]


In [5]:
print(x+2)

[ 3.   5.  10.   6.9 14. ]


In [6]:
print(x*2)

[ 2.   6.  16.   9.8 24. ]


- **Arithmetic Operations with Two Arrays**

In [7]:
import numpy as np 
liste_1 = [1,3,5,7]
liste_2 = [2,4,6,8]
dizi_1 = np.array(liste_1)
dizi_2 = np.array(liste_2)
print(dizi_1,dizi_2)

[1 3 5 7] [2 4 6 8]


In [8]:
print(dizi_1 + dizi_2)

[ 3  7 11 15]


In [9]:
print(dizi_1 * dizi_2)

[ 2 12 30 56]


- **Comparison Operators**

In [10]:
import numpy as np
y = np.arange(1,7)
print(y)

[1 2 3 4 5 6]


In [11]:
print(y>3)

[False False False  True  True  True]


In [12]:
print(y>=3)

[False False  True  True  True  True]


In [13]:
print(y!=3)

[ True  True False  True  True  True]


In [14]:
print(y==3)

[False False  True False False False]


In [15]:
a = np.arange(0,10,2)
b = np.arange(0,15,3)
print(a)
print(b)                    #To work with two arrays, the arrays must be the same size

[0 2 4 6 8]
[ 0  3  6  9 12]


In [16]:
print(a<b)

[False  True  True  True  True]


In [17]:
print(a>=b)

[ True False False False False]


In [18]:
print(a!=b)

[False  True  True  True  True]


In [19]:
print(a==b)

[ True False False False False]


-**Logical Operators**

In [20]:
#1- np.logical_and

import numpy as np
print(np.logical_and(True,True))
print(np.logical_and(True,False))
print(np.logical_and(False,False))

True
False
False


In [21]:
array_1 = np.arange(2,15,3)
print(array_1)

[ 2  5  8 11 14]


In [22]:
print(np.logical_and(array_1>2,array_1<11))

[False  True  True False False]


In [23]:
print(np.logical_and(array_1>=5,array_1<13))

[False  True  True  True False]


In [24]:
#2- np.logical_or

print(np.logical_or(True,True))
print(np.logical_or(True,False))
print(np.logical_or(False,False))

True
True
False


In [25]:
print(array_1)

[ 2  5  8 11 14]


In [26]:
print(np.logical_or(array_1>2,array_1<11))

[ True  True  True  True  True]


In [27]:
print(np.logical_or(array_1>=5,array_1<13))

[ True  True  True  True  True]


In [0]:
...