In [1]:
import numpy as np
x = np.arange(2,20,2)
print(x)

[ 2  4  6  8 10 12 14 16 18]


In [3]:
print(x[0])
print(x[1])
print(x[2])

2
4
6


In [5]:
print(x.size)  #number of elements

9


In [9]:
#  array[ start(including) : stop(excluding) : step ]

print(x[0:9:1])
print(x[0:8:1])
print(x[2:9:1])
print(x[0:9:2])

[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16]
[ 6  8 10 12 14 16 18]
[ 2  6 10 14 18]


- **Filling certain indexes with desired value**

In [31]:
y = np.arange(2,22,2)
print(y)

[ 2  4  6  8 10 12 14 16 18 20]


In [32]:
y[0:10:2]=0
print(y)

[ 0  4  0  8  0 12  0 16  0 20]


In [34]:
y[1:10:2]=1
print(y)

[0 1 0 1 0 1 0 1 0 1]


In [35]:
y[:3]=4   
print(y)

[4 4 4 1 0 1 0 1 0 1]


- **Advanced indexing**

Working logic : array_name[row_indexes , column_indexes]

In [51]:
array_1 = [[1,2],
           [3,4]]

z = np.array(array_1)
print(z)

[[1 2]
 [3 4]]


In [40]:
print(z[0,0])

1


In [41]:
print(z[0,1])

2


In [42]:
print(z[1,0])

3


In [43]:
print(z[1,1])

4


In [48]:
print(z[[0,0],[0,1]])

[1 2]


In [49]:
print(z[[1,1],[0,1]])

[3 4]
