- **Basic**

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3, 5)

In [6]:
a.size

15

- **Linspace** **&** **Arange**

In [7]:
import numpy as np
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [8]:
b = np.arange(0,50,5)
print(b)

[ 0  5 10 15 20 25 30 35 40 45]


In [9]:
x = np.linspace(1,10)
print(x)                     #Generates 50 evenly spaced values from 1-10

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [10]:
y = np.linspace(1,10,7)
print(y)                     #1-10 arası eşit aralıklı 7 değer üretti

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [11]:
samples, spacing = np.linspace(1,10,num=5,retstep=True)
print("Üretilenler: ",samples)
print("Aralık" , spacing)

Üretilenler:  [ 1.    3.25  5.5   7.75 10.  ]
Aralık 2.25


- **Random Sampling**

In [12]:
import numpy as np
np.random.rand()        #0-1 arası rastgele bir sayı üretir

0.9342677963802369

In [13]:
np.random.rand(3,2)

array([[0.16122161, 0.34134332],
       [0.2873687 , 0.41248797],
       [0.61687006, 0.42049995]])

In [14]:
np.random.randint(0,2,size=4)      #0(dahil)-2(hariç) aralığında rastgele 4 sayı üretir

array([1, 1, 0, 1])

In [15]:
isimler =["Ali","Ayşe,","Fatma","İsmail"]
np.random.choice(isimler,size=(3,3))

array([['Fatma', 'Ali', 'İsmail'],
       ['İsmail', 'Fatma', 'Ayşe,'],
       ['Ayşe,', 'Ayşe,', 'Ayşe,']], dtype='<U6')

- **Zeros,Ones,Full**

In [16]:
import numpy as np
np.zeros(5,dtype=int)    #5 tane float 0 oluşturur.dtype=int komutuyla integer'a dönüştürülebilir

array([0, 0, 0, 0, 0])

In [17]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [18]:
np.full((3,3),"Mehmet")

array([['Mehmet', 'Mehmet', 'Mehmet'],
       ['Mehmet', 'Mehmet', 'Mehmet'],
       ['Mehmet', 'Mehmet', 'Mehmet']], dtype='<U6')